# Generated by Django 5.0.4 on 2024-04-29 13:28

import django.db.models.deletion
import timetable_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='faculty')),
                ('code_faculty', models.CharField(max_length=50, verbose_name='code faculty')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
                'db_table': 'faculty',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(verbose_name='day')),
                ('precise_time', models.TimeField(verbose_name='precise time')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'db_table': 'lesson',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'db_table': 'subject',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='group')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.faculty', verbose_name='faculty')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'class',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LessonToGroup',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_app.group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.lesson')),
            ],
            options={
                'db_table': 'lesson_to_class',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(through='timetable_app.LessonToGroup', to='timetable_app.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons',
            field=models.ManyToManyField(through='timetable_app.LessonToGroup', to='timetable_app.lesson', verbose_name='lessons'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('group', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.group', verbose_name='group')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'student',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.subject', verbose_name='subject'),
        ),
        migrations.CreateModel(
            name='SubjectToGroup',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_app.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.subject')),
            ],
            options={
                'db_table': 'subject_to_class',
                'unique_together': {('subject', 'group')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(through='timetable_app.SubjectToGroup', to='timetable_app.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(through='timetable_app.SubjectToGroup', to='timetable_app.subject', verbose_name='subjects'),
        ),
        migrations.CreateModel(
            name='SubjectToTeacher',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.subject')),
            ],
            options={
                'db_table': 'subject_to_teacher',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('faculty', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timetable_app.faculty', verbose_name='faculty')),
                ('subjects', models.ManyToManyField(through='timetable_app.SubjectToTeacher', to='timetable_app.subject', verbose_name='subjects')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teacher',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='subjecttoteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(through='timetable_app.SubjectToTeacher', to='timetable_app.teacher', verbose_name='teachers'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.teacher', verbose_name='teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='subjecttoteacher',
            unique_together={('subject', 'teacher')},
        ),
    ]
