# Generated by Django 5.0.4 on 2024-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='end time'),
        ),
    ]
