# Generated by Django 5.0.4 on 2024-04-29 20:07

import timetable_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonToGroup',
            new_name='LessonGroup',
        ),
        migrations.RenameModel(
            old_name='SubjectToGroup',
            new_name='SubjectGroup',
        ),
        migrations.RenameModel(
            old_name='SubjectToTeacher',
            new_name='SubjectTeacher',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['start_time'], 'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='precise_time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='faculty',
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(default=timetable_app.models.get_datetime, verbose_name='start time'),
        ),
        migrations.AlterModelTable(
            name='lessongroup',
            table='lesson_group',
        ),
        migrations.AlterModelTable(
            name='subjectgroup',
            table='subject__group',
        ),
        migrations.AlterModelTable(
            name='subjectteacher',
            table='subject_teacher',
        ),
    ]
