# Generated by Django 5.0.4 on 2024-05-11 09:06

import django.db.models.deletion
import timetable_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_alter_lesson_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=90, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(default=timetable_app.models.get_datetime, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_app.teacher', verbose_name='teacher'),
        ),
    ]
