# Generated by Django 5.0.4 on 2024-05-11 15:50

import timetable_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0003_alter_lesson_duration_alter_lesson_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='created',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='modified',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='group',
            name='modified',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='modified',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='student',
            name='modified',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='subject',
            name='modified',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_modified], verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='created',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='created',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_created], verbose_name='created'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='modified',
            field=models.DateTimeField(blank=True, default=timetable_app.models.get_datetime, null=True, validators=[timetable_app.models.check_modified], verbose_name='modified'),
        ),
    ]
