name: Main test
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8

  container-job:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Dependencies installation
      run: |
        python3 -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        chmod +x tests/test.sh
    - name: Test views
      run: ./tests/test.sh tests.test_views
    - name: Test models
      run: ./tests/test.sh tests.test_models
    - name: Test rest
      run: ./tests/test.sh tests.test_rest
    - name: Test validations
      run: ./tests/test.sh tests.test_validations